name: Modularity
favicon: null
layout_spectrum: 0.50226
typography_spectrum: 0.33827
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#100f17'
    - '#37464d'
    - '#c7c2be'
    - '#84756b'
  brandStrength: 0.5625
  lightness: 0.625
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
